package com.bobble.bobblesampleapp.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gifsDaoConfig;
    private final DaoConfig stickerDaoConfig;

    private final GifsDao gifsDao;
    private final stickerDao stickerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gifsDaoConfig = daoConfigMap.get(GifsDao.class).clone();
        gifsDaoConfig.initIdentityScope(type);

        stickerDaoConfig = daoConfigMap.get(stickerDao.class).clone();
        stickerDaoConfig.initIdentityScope(type);

        gifsDao = new GifsDao(gifsDaoConfig, this);
        stickerDao = new stickerDao(stickerDaoConfig, this);

        registerDao(Gifs.class, gifsDao);
        registerDao(Sticker.class, stickerDao);
    }
    
    public void clear() {
        gifsDaoConfig.getIdentityScope().clear();
        stickerDaoConfig.getIdentityScope().clear();
    }

    public GifsDao getGifsDao() {
        return gifsDao;
    }

    public stickerDao getStickerDao() {
        return stickerDao;
    }

}
