package com.bobble.bobblesampleapp.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOG_EVENTS".
 */
public class LogEvents {

    private Long id;
    /** Not-null value. */
    private String screenName;
    /** Not-null value. */
    private String eventAction;
    /** Not-null value. */
    private String eventName;
    /** Not-null value. */
    private String eventLabel;
    private long eventTimestamp;
    /** Not-null value. */
    private String status;

    public LogEvents() {
    }

    public LogEvents(Long id) {
        this.id = id;
    }

    public LogEvents(Long id, String screenName, String eventAction, String eventName, String eventLabel, long eventTimestamp, String status) {
        this.id = id;
        this.screenName = screenName;
        this.eventAction = eventAction;
        this.eventName = eventName;
        this.eventLabel = eventLabel;
        this.eventTimestamp = eventTimestamp;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getScreenName() {
        return screenName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    /** Not-null value. */
    public String getEventAction() {
        return eventAction;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEventAction(String eventAction) {
        this.eventAction = eventAction;
    }

    /** Not-null value. */
    public String getEventName() {
        return eventName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /** Not-null value. */
    public String getEventLabel() {
        return eventLabel;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEventLabel(String eventLabel) {
        this.eventLabel = eventLabel;
    }

    public long getEventTimestamp() {
        return eventTimestamp;
    }

    public void setEventTimestamp(long eventTimestamp) {
        this.eventTimestamp = eventTimestamp;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

}
