package com.bobble.bobblesampleapp.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STICKER".
 */
public class Sticker {

    private long id;
    private String stickerName;
    private String path;
    private Boolean isAd;

    public Sticker() {
    }

    public Sticker(long id) {
        this.id = id;
    }

    public Sticker(long id, String stickerName, String path, Boolean isAd) {
        this.id = id;
        this.stickerName = stickerName;
        this.path = path;
        this.isAd = isAd;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getStickerName() {
        return stickerName;
    }

    public void setStickerName(String stickerName) {
        this.stickerName = stickerName;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Boolean getIsAd() {
        return isAd;
    }

    public void setIsAd(Boolean isAd) {
        this.isAd = isAd;
    }

}
